apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-gateway-cert
  namespace: istio-system
spec:
  secretName: {{ .Values.certificates.ingress.secretName }}
  dnsNames:
    {{- range .Values.certificates.ingress.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: egress-gateway-cert
  namespace: istio-system
spec:
  secretName: {{ .Values.certificates.egress.secretName }}
  dnsNames:
    {{- range .Values.certificates.egress.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
