apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "cormorant.drewpy.pro"
    - "anhinga.drewpy.pro"
    - "gannet.drewpy.pro"
    - "argocd.drewpy.pro"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "cormorant.drewpy.pro"
    - "anhinga.drewpy.pro"
    - "gannet.drewpy.pro"
    - "argocd.drewpy.pro"
    tls:
      mode: SIMPLE
      credentialName: ingress-gateway-cert

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-gateway
  namespace: istio-ingress
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 30443
      protocol: TCP
    - name: healthz
      port: 15021
      targetPort: 15021
      nodePort: 31170
      protocol: TCP
  selector:
    app: istio-ingressgateway
