# Istio Ingress Gateway configuration
gateways:
  istio-ingressgateway:
    name: istio-ingressgateway
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    ports:
      - port: 15021
        targetPort: 15021
        nodePort: 31170
        name: status-port
        protocol: TCP
      - port: 80
        targetPort: 8080
        name: http
        protocol: TCP
        nodePort: 30080
      - port: 443
        targetPort: 8443
        name: https
        protocol: TCP
        nodePort: 30443
    type: NodePort
    secretVolumes:
      - name: ingressgateway-certs
        secretName: ingress-gateway-cert
        mountPath: /etc/istio/ingressgateway-certs
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

# Traffic management resources
traffic:
  gateways:
    - name: ingress-gateway
      namespace: istio-system
      servers:
        - port:
            number: 80
            name: http
            protocol: HTTP
          hosts:
            - "cormorant.drewpy.pro"
            - "anhinga.drewpy.pro"
            - "gannet.drewpy.pro"
            - "argocd.drewpy.pro"
          tls:
            httpsRedirect: true
        - port:
            number: 443
            name: https
            protocol: HTTPS
          hosts:
            - "cormorant.drewpy.pro"
            - "anhinga.drewpy.pro"
            - "gannet.drewpy.pro"
            - "argocd.drewpy.pro"
          tls:
            mode: SIMPLE
            credentialName: ingress-gateway-cert
  virtualServices:
    - name: argocd
      namespace: istio-system
      hosts:
        - "argocd.drewpy.pro"
      gateways:
        - ingress-gateway
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: argocd-server
                port:
                  number: 443
