profile: default

ingressGateway:
  name: ingress-gateway
  ports:
    - name: http
      port: 80
      targetPort: 30080
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 30443
      nodePort: 30443
    - name: healthz
      port: 15021
      targetPort: 15021
      nodePort: 31170
  hosts:
    - "cormorant.drewpy.pro"
    - "anhinga.drewpy.pro"
    - "gannet.drewpy.pro"
    - "argocd.drewpy.pro"
  credentialName: ingress-gateway-cert

egressGateway:
  name: egress-gateway
  hosts:
    - "*"
  credentialName: egress-gateway-cert

virtualServices:
  argocd:
    host: "argocd.drewpy.pro"
    service: "argocd-server"
    port: 443