service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "{{NLB_SG_ID}}"
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: healthz
      port: 15021
      targetPort: 15021
      nodePort: 31170

deployment:
  nodeSelector:
    role: istio-ingress
  tolerations:
    - key: dedicated
      operator: Equal
      value: istio-ingress
      effect: NoSchedule
