service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-0c2523fabe69d96a7"
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
  - name: healthz
    port: 15021
    targetPort: 15021
    nodePort: 31170
    protocol: TCP

nodeSelector:
  role: istio-ingress

tolerations:
  - key: dedicated
    operator: Equal
    value: istio-ingress
    effect: NoSchedule