apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
      - name: ingress-gateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - name: https
                port: 443
                targetPort: 30443
                nodePort: 30443
              - name: https
                port: 443
                targetPort: 30443
                nodePort: 30443
              - name: healthz
                port: 15021
                targetPort: 15021
                nodePort: 31170
              - name: argocd
                port: 8080
                targetPort: 38080
                nodePort: 38080