apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: argocd
  labels:
    app: debug
spec:
  containers:
  - name: debug-container
    image: nicolaka/netshoot
    command:
    - /bin/sh
    - -c
    - "while true; do sleep 30; done;"
    securityContext:
      privileged: true  
      capabilities:
        add:
        - NET_ADMIN  
        - SYS_ADMIN
    stdin: true
    tty: true
  restartPolicy: Always
