apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:latest
        ports:
        - containerPort: 8080
        env:
        - name: ARGOCD_SERVER_REPO_CREDENTIALS
          value: "false"
        command:
        - argocd-server
        args:
        - --staticassets
        - /shared/app
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        volumeMounts:
        - name: argocd-cm-volume
          mountPath: /etc/argocd-cm
          readOnly: true
      volumes:
      - name: argocd-cm-volume
        configMap:
          name: argocd-cm
