apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service2-virtual-service
  namespace: namespace2
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/ingress-gateway
  http:
  - match:
    - uri:
        prefix: "/app2"
    route:
    - destination:
        host: app2
        port:
          number: 80
