apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service1-virtual-service
  namespace: namespace1
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - port: 30080
          uri:
            prefix: "/app1"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: app1
            port:
              number: 80
