apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.egressGateway.name }}
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.egressGateway.credentialName }}
    hosts:
      {{- range .Values.egressGateway.hosts }}
      - {{ . }}
      {{- end }}
