apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: {{ .Values.profile }}
  components:
    ingressGateways:
      - name: {{ .Values.ingressGateway.name }}
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              {{- range .Values.ingressGateway.ports }}
              - name: {{ .name }}
                port: {{ .port }}
                targetPort: {{ .targetPort }}
                nodePort: {{ .nodePort }}
              {{- end }}
