apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtual-service
  namespace: argocd
spec:
  hosts:
    - {{ .Values.virtualServices.argocd.host }}
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - route:
        - destination:
            host: {{ .Values.virtualServices.argocd.service }}
            port:
              number: {{ .Values.virtualServices.argocd.port }}
