apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gannet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewpypro/gannet
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: gannet-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
