apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: namespace1
  labels:
    app: app1
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
