apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: namespace2
  labels:
    app: app2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
