apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-087aee6c3b7000396"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-090dbfa86511370ba,subnet-0942dd9c1c29faeaa"
spec:
  selector:
    app: istio-ingressgateway
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443