# apiVersion: v1
# kind: Service
# metadata:
#   name: istio-ingressgateway
#   namespace: istio-system
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-0feabbeef667b3d17
# spec:
#   type: LoadBalancer
#   selector:
#     app: istio-ingressgateway
#   ports:
#     - port: 80
#       targetPort: 80
#     - port: 443
#       targetPort: 443
