apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "nlb_sg_id"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "nlb_subnet_1,nlb_subnet_2"
spec:
  selector:
    app: istio-ingressgateway
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443