apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 30080
      name: nodeport-http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 15021
      name: healthz
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 30443
      name: nodeport-https
      protocol: HTTP
    hosts:
    - "*"
