apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "cormorant.drewpy.pro"
    - "anhinga.drewpy.pro"
    - "gannet.drewpy.pro"
    - "argocd.drewpy.pro"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "cormorant.drewpy.pro"
    - "anhinga.drewpy.pro"
    - "gannet.drewpy.pro"
    - "argocd.drewpy.pro"
    tls:
      mode: SIMPLE
      credentialName: ingress-gateway-cert
