apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: egress-gateway-cert
  namespace: istio-system
spec:
  secretName: egress-gateway-cert
  dnsNames:
    - "egress.drewpy.pro"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
